# Generated by Django 4.2.7 on 2023-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=150)),
                ('stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualification', 'Qualification'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed - Won', 'Closed - Won'), ('Closed - Lost', 'Closed - Lost')], max_length=20)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Probability of closing in percentage')),
            ],
        ),
    ]
