# Generated by Django 4.2.7 on 2023-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('billing_country', models.CharField(max_length=50)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('account_description', models.TextField(blank=True, null=True)),
                ('account_history', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
